### ISSUE TITLE
osx 10.10.4, electron 0.30.2, following tutorial steps to bundle ceramic-hello-world fails

### ISSUE THREAD

**Issue by jkordani** [ceramic/ceramic#12]
backtrace

Is a directory : #P"/Users/joshua/.ceramic/electron/Electron.app/Contents/Frameworks/Electron Framework.framework/Libraries"
   [Condition of type CCL::SIMPLE-FILE-ERROR]

Restarts:
 0: [RETRY-OPEN] Retry opening #P"/Users/joshua/.ceramic/electron/Electron.app/Contents/Frameworks/Electron Framework.framework/Libraries"
 1: [RETRY] Retry SLIME REPL evaluation request.
 2: [*ABORT] Return to SLIME's top level.
 3: [ABORT-BREAK] Reset this thread
 4: [ABORT] Kill this thread

Backtrace:
  0: (CCL::MAKE-FILE-STREAM #P"/Users/joshua/.ceramic/electron/Electron.app/Contents/Frameworks/Electron Framework.framework/Libraries" :INPUT (INTEGER 0 255) :IGNORED :ERROR FILE-STREAM :DEFAULT :PRIVATE ..
  1: (OPEN #P"/Users/joshua/.ceramic/electron/Electron.app/Contents/Frameworks/Electron Framework.framework/Libraries" :DIRECTION :INPUT :ELEMENT-TYPE (UNSIGNED-BYTE 8) :IF-EXISTS :ERROR :IF-DOES-NOT-EXIST..
  2: (UIOP/STREAM:CONCATENATE-FILES (#P"/Users/joshua/.ceramic/electron/Electron.app/Contents/Frameworks/Electron Framework.framework/Libraries") #P"/Users/joshua/.ceramic/working/electron/Electron.app/Con..
  3: ((:INTERNAL CL-FAD::WALK CL-FAD:WALK-DIRECTORY) #P"/Users/joshua/.ceramic/electron/Electron.app/Contents/Frameworks/Electron Framework.framework/")
  4: ((:INTERNAL CL-FAD::WALK CL-FAD:WALK-DIRECTORY) #P"/Users/joshua/.ceramic/electron/Electron.app/Contents/Frameworks/")
  5: ((:INTERNAL CL-FAD::WALK CL-FAD:WALK-DIRECTORY) #P"/Users/joshua/.ceramic/electron/Electron.app/Contents/")
  6: ((:INTERNAL CL-FAD::WALK CL-FAD:WALK-DIRECTORY) #P"/Users/joshua/.ceramic/electron/Electron.app/")
  7: ((:INTERNAL CL-FAD::WALK CL-FAD:WALK-DIRECTORY) #P"/Users/joshua/.ceramic/electron/")
  8: (CL-FAD:WALK-DIRECTORY #P"/Users/joshua/.ceramic/electron/" #<COMPILED-LEXICAL-CLOSURE (:INTERNAL CERAMIC.UTIL:COPY-DIRECTORY) #x3020041A962F> :DIRECTORIES :BREADTH-FIRST :IF-DOES-NOT-EXIST :ERROR :TE..
  9: (CERAMIC.UTIL:COPY-DIRECTORY #P"/Users/joshua/.ceramic/electron/" #P"/Users/joshua/.ceramic/working/electron/")
 10: (CERAMIC.BUNDLER:BUNDLE :CERAMIC-HELLO-WORLD :BUNDLE-PATHNAME NIL)
 11: (CCL::CALL-CHECK-REGS CERAMIC.BUNDLER:BUNDLE :CERAMIC-HELLO-WORLD)
 12: (CCL::CHEAP-EVAL (CERAMIC.BUNDLER:BUNDLE :CERAMIC-HELLO-WORLD))
 --more--

**Comment by eudoxia0** [comment]
Odd. I wonder if it's in the actual file copying code or the directory walker.

**Comment by glider-gun** [comment]
I think the reason is `fad:walk-directory` in `copy-directory` is not aware of symbolic-link and treats them as ordinary directory.
Perhaps it is necessary to reimplement `copy-directory` with symbolic-link aware library such as [osicat](https://common-lisp.net/project/osicat/manual/osicat.html#Files-and-Symbolic-Links).

**Comment by glider-gun** [comment]
I think I have time to try it out this weekend.

**Comment by cmm101** [comment]
It's most likely a sim link problem like you said:

error opening #P"/Users/codymallery/.ceramic/electron/Electron.app/Contents/Frameworks/Electron Framework.framework/Libraries/Libraries":
  No such file or directory
   [Condition of type SB-INT

Cody-Mallerys-MacBook-Pro:Libraries codymallery$ pwd
/Users/codymallery/.ceramic/electron/Electron.app/Contents/Frameworks/Electron Framework.framework/Libraries
Cody-Mallerys-MacBook-Pro:Libraries codymallery$ ls -all
total 35184
drwxr-xr-x  5 codymallery  wheel       170 Jun 12 04:39 .
drwxr-xr-x  5 codymallery  wheel       170 Jun 12 04:39 ..
lrwxr-xr-x  1 codymallery  wheel        26 Aug  6 16:10 Libraries -> Versions/Current/Libraries
-rw-r--r--  1 codymallery  wheel   2465176 Jun  4 09:37 ffmpegsumo.so
-rwxr-xr-x  1 codymallery  wheel  15542064 Jun 12 04:29 libnode.dylib
Cody-Mallerys-MacBook-Pro:Libraries codymallery$ cd Libraries 
-bash: cd: Libraries: No such file or directory
Cody-Mallerys-MacBook-Pro:Libraries codymallery$ ls
Libraries   ffmpegsumo.so   libnode.dylib
Cody-Mallerys-MacBook-Pro:Libraries codymallery$

**Comment by jkordani** [comment]
I believe that the latest version of the electron dist has cleaned out the dangling simlink.

**Comment by jkordani** [comment]
i believe that the current version of electron has this dangling sim link removed.

**Comment by cmm101** [comment]
Ok I'll look into that, dangling sim links ruin everything.
