### ISSUE TITLE
Tutorial - The value NIL is not of type SB-IMPL::PROCESS.

### ISSUE THREAD

**Issue by cmm101** [ceramic/ceramic#15]
SBCL 1.2.14

It expects a type SB-IMPL::PROCESS but it's getting a NIL instead.

It happens inside the run function after my break statement:
`(defun run ()
  (break)
  (setf *window*
        (ceramic:make-window :url (format nil "http://localhost:~D/" *port*)))
  (ceramic:show-window *window*)
  (start app :port *port*))`

`Backtrace:
  0: ((:METHOD EXTERNAL-PROGRAM:PROCESS-INPUT-STREAM (T)) NIL) [fast-method]
      Locals:
        SB-DEBUG::ARG-2 = NIL

  1: (CERAMIC.ELECTRON:SEND-COMMAND NIL "create-window" (("name" . "urn:uuid:1cde3164-58cb-4ca0-8552-73eb0b6aa195") ("show" :FALSE) ("resizable" . T)))
      Locals:
        SB-DEBUG::ARG-0 = NIL
        SB-DEBUG::ARG-1 = "create-window"
        SB-DEBUG::ARG-2 = (("name" . "urn:uuid:1cde3164-58cb-4ca0-8552-73eb0b6aa195") ("show" :FALSE) ("resizable" . T))`

**Comment by eudoxia0** [comment]
Try starting the electron executable in the `.ceramic/electron/` directory and see if it fails on startup.

**Comment by cmm101** [comment]
It turns out _process_ was nil because (ceramic:interactive) was not ran. This can be closed.

**Comment by eudoxia0** [comment]
Heh, I do that all the time.

**Comment by cmm101** [comment]
I can see how that would happen. I got to brush up on my debugging skills so all is well. all I had to do was dig deep into ceramic.electron.

This is fantastic, keep up the good work.

**Comment by eudoxia0** [comment]
:+1:
