### ISSUE TITLE
OSX 10.9.5 ceramic does not connect to hunchentoot process with (markedit:start-app)

### ISSUE THREAD

**Issue by cmm101** [ceramic/ceramic#17]
I run the following commands and hunchentoot starts up but ceramic does not connect to hunchentoot and an electron window does not come up with markedit inside.

the electron process and electron helper do not start

I can however go to localhost:40000 inside chrome and use the app.

Could it be an older version of ceramic or markedit on the quicklisp server?

I can run the other examples no problem.

if I run these lines I can make the electron window open:

`(defvar run-it (ceramic:make-window :url (format nil "http://localhost:~D/" *port*)))`
`(ceramic:show-window run-it)`

this means that:

when `(markedit:start-app)` is evaluated the first break inside `(define-entry-point :markedit)` triggers but the second break does not ...meaning that the `(let....)` is never evaluated and the window is never created.

`(ceramic:define-entry-point :markedit ()`
  `(break)`
  `(let ((window (ceramic:make-window :url (format nil "http://localhost:~D/" *port*))))`
   `(break)`
    `(ceramic:show-window window)`
   `(start-app)))`

; SLIME 2015-07-18
CL-USER> (ql:quickload '(ceramic markedit))
To load "ceramic":
  Load 1 ASDF system:
    ceramic
; Loading "ceramic"
........................
To load "markedit":
  Load 1 ASDF system:
    markedit
; Loading "markedit"
.....................................
(CERAMIC MARKEDIT)
CL-USER> (ceramic:interactive)
T
CL-USER> (markedit:start-app)
Hunchentoot server is started.
Listening on localhost:40000.
T

**Comment by eudoxia0** [comment]
Hmm, try starting the app before showing the window, and adding a small timeout.

**Comment by cmm101** [comment]
Starting the app with start-app even after switching the orders of things still does not work but this works:

So I suppose you could then just edit the entry point function to call start-application instead of start-app.

Here's a quickfix:

`(defun start-application ()`
  `(let ((window (ceramic:make-window :url (format NIL "http://localhost:~D/" *port*))))`
    `(start-app)`
    `(ceramic:show-window window)))`

MARKEDIT> (ceramic:interactive)

T
MARKEDIT> (start-application)
Hunchentoot server is started.
Listening on localhost:40000.
"{\"cmd\":\"show-window\",\"name\":\"urn:uuid:ecd3737f-b9ab-4e61-b3db-79cdc9fcc534\"}"
MARKEDIT>
