### ISSUE TITLE
ceramic with CCL on Windows 10 64-bit can't compile.

### ISSUE THREAD

**Issue by dertuxmalwieder** [ceramic/ceramic#18]
Trying to follow the [tutorial](http://ceramic.github.io/docs/tutorial.html) with Clozure CL fails at the `(ql:quickload :ceramic)` point:

```
..> Error: The value #P"buildapp.exe" is not of the expected type SEQUENCE.
```

I can just skip this error, but things are becoming worse then (more errors, no successful system built). Can I help you to fix that somehow? (I'm new to the Lisp things but not to Windows.)

**Comment by eudoxia0** [comment]
Alright. Let me install CCL and see if I get the same thing on Linux. I suspect it might be a pathname parsing thing.

**Comment by dertuxmalwieder** [comment]
On Linux you won't have a "buildapp.exe". I don't know if you can reproduce it this way.

**Comment by eudoxia0** [comment]
Wait, try quickloading `:buildapp` before ceramic, and run `(buildapp:build-buildapp #p"some/path.exe")`.

**Comment by dertuxmalwieder** [comment]
Well...

```
? (ql:quickload :buildapp)
 To load "buildapp":
  Load 1 ASDF system:
    buildapp
> Error: The value #P"buildapp.exe" is not of the expected type SEQUENCE.
```

**Comment by eudoxia0** [comment]
ping @xach

**Comment by dertuxmalwieder** [comment]
That does not mean that a fixed `buildapp` will make Ceramic work yet. :P

**Comment by eudoxia0** [comment]
No, certainly not, but it's a start.

**Comment by xach** [comment]
Sorry about the buildapp problem. The ccl support has been pretty shaky. I'm partway through completely rewriting it, but I'll try to make a small fix to the current code to avoid this issue.

**Comment by dertuxmalwieder** [comment]
Great, thanks. Keep us posted. :-)

(I don't really want to change my runtime just for that.)

**Comment by dertuxmalwieder** [comment]
Any updates?

**Comment by dertuxmalwieder** [comment]
^ that fix fixed this very error for me. :)

**Comment by eudoxia0** [comment]
Awesome, I don't have to finish trivial-build

**Comment by dertuxmalwieder** [comment]
Depends. There is still #19 ...
