### ISSUE TITLE
ceramic with CCL can't run "setup".

### ISSUE THREAD

**Issue by dertuxmalwieder** [ceramic/ceramic#19]
Another Clozure CL experience; but it breaks at a later point as `buildapp` builds fine on this machine:

```
? (ceramic:setup)
Creating Ceramic directories...
Installing Buildapp...
> Error: The value NIL is not of the expected type REAL.
> While executing: CCL::>-2, in process listener(1).
> Type :POP to abort, :R for a list of available restarts.
> Type :? for other options.
```

**Comment by eudoxia0** [comment]
Can you run it on SLIME or otherwise get a stack trace? I'd like to see exactly where it fails.

**Comment by dertuxmalwieder** [comment]
SLIME stacktrace:

```
0: ((:INTERNAL BUILDAPP::MAIN) #<BASIC-FILE-CHARACTER-OUTPUT-STREAM ("dumper-f0dIhgSY.lisp"/4 UTF-8) #x3020026AB17D> #P"dumper-f0dIhgSY.lisp")
1: (BUILDAPP::CALL-WITH-TEMPORARY-OPEN-FILE "dumper.lisp" #<COMPILED-LEXICAL-CLOSURE (:INTERNAL BUILDAPP::MAIN) #x3020026AB98F>)
2: (BUILDAPP::MAIN ("sbcl" "--asdf-path" "/Users/username/quicklisp/dists/quicklisp/software/buildapp-1.5.4/" "--load-system" "buildapp" "--entry" ...))
3: (CERAMIC.SETUP:SETUP)
4: (CCL::CALL-CHECK-REGS CERAMIC:SETUP)
5: (CCL::CHEAP-EVAL (CERAMIC:SETUP))
```

(2) seems to me that it still wants to load `sbcl` natively which is, of course, wrong.

**Comment by eudoxia0** [comment]
I should really switch away from Buildapp to ASDF's executable build thing.

@xach how does Buildapp determine which implementation to run?

**Comment by xach** [comment]
Buildapp uses the implementation it was built with, which is pretty silly, and not in the new design.

**Comment by dertuxmalwieder** [comment]
What is the reason to use Buildapp anyway?

-e- But I built Buildapp with `ccl`...

**Comment by eudoxia0** [comment]
Well, I need to compile the application to an executable to bundle it.

I suppose I could string something together with [lisp-invocation](http://quickdocs.org/lisp-invocation/).

**Comment by dertuxmalwieder** [comment]
Ah, now I get the point, sorry.

(I won't have access to the OSX machine for two weeks now FYI. Still happy to test on Windows.)

**Comment by dertuxmalwieder** [comment]
FYI, I get the same error on Windows 10 x64 after patching #18. Updating this ticket.

**Comment by eudoxia0** [comment]
Is the backtrace the same?

**Comment by dertuxmalwieder** [comment]
Well, of course the paths are different (above are OSX paths), but the command is the same: It still thinks I want to use `sbcl`.

```
Backtrace:
  0: ((:INTERNAL MAIN) #<BASIC-FILE-CHARACTER-OUTPUT-STREAM ("dumper-f0dIhgSY.lisp"/6528 UTF-8) #x210279D30D> #P"dumper-f0dIhgSY.lisp")
  1: (CALL-WITH-TEMPORARY-OPEN-FILE "dumper.lisp" #<CCL:COMPILED-LEXICAL-CLOSURE (:INTERNAL MAIN) #x210279DC2F>)
  2: (MAIN ("sbcl" "--asdf-path" "C:/Users/hp/quicklisp/local-projects/buildapp/" "--load-system" "buildapp" "--entry" ...))
  3: (CERAMIC.SETUP:SETUP)
  4: (CCL::CALL-CHECK-REGS CERAMIC:SETUP)
  5: (CCL::TOPLEVEL-EVAL (CERAMIC:SETUP) NIL)
  6: (CCL::READ-LOOP :INPUT-STREAM #<SYNONYM-STREAM to *TERMINAL-IO* #x210040E25D> :OUTPUT-STREAM #<SYNONYM-STREAM to *TERMINAL-IO* #x210040E0FD> :BREAK-LEVEL 0 :PROMPT-FUNCTION #<Compiled-function (:INTER..
  7: (CCL::RUN-READ-LOOP :BREAK-LEVEL 0)
  8: (CCL:TOPLEVEL-LOOP)
  9: ((:INTERNAL (CCL:TOPLEVEL-FUNCTION (CCL::LISP-DEVELOPMENT-SYSTEM T))))
 10: ((:INTERNAL CCL::MAKE-MCL-LISTENER-PROCESS))
 11: (CCL::RUN-PROCESS-INITIAL-FORM #<TTY-LISTENER listener(1) [Active] #x210040D07D> (#<CCL:COMPILED-LEXICAL-CLOSURE (:INTERNAL CCL::MAKE-MCL-LISTENER-PROCESS) #x210040CBAF>))
 12: ((:INTERNAL (CCL::%PROCESS-PRESET-INTERNAL (CCL:PROCESS))) #<TTY-LISTENER listener(1) [Active] #x210040D07D> (#<CCL:COMPILED-LEXICAL-CLOSURE (:INTERNAL CCL::MAKE-MCL-LISTENER-PROCESS) #x210040CBAF>))
 13: ((:INTERNAL CCL::THREAD-MAKE-STARTUP-FUNCTION))
```

**Comment by eudoxia0** [comment]
huh

**Comment by eudoxia0** [comment]
Well, Christ, I guess I'll have to look into ASDF's builder thing.

**Comment by dertuxmalwieder** [comment]
Heh. Sorry. I'm happy to help you out with any backtraces you need.

**Comment by eudoxia0** [comment]
Well, trivial-build works for 'normal' implementations, just not Roswell ones (because of saved-core fuckery). I guess I could merge that into Ceramic.

**Comment by dertuxmalwieder** [comment]
Which ones are the Roswell ones? First time I see that.

**Comment by eudoxia0** [comment]
Roswell is the impl. manager I use for Travis testing. If someone uses it to build a Ceramic app it will get all borked.

**Comment by dertuxmalwieder** [comment]
Heh. Good to know. Well... I thought you'd to trivial-build anyway?

**Comment by eudoxia0** [comment]
Well, I don't think it matters, really. It's a corner case.

I'll finish this up tomorrow because I need to get some sleep, nini

**Comment by dertuxmalwieder** [comment]
Good night :)

**Comment by eudoxia0** [comment]
Okay, I've merged trivial-build. Can you try building this again?

**Comment by dertuxmalwieder** [comment]
edit: Ah, I see. I seem to require your whole GitHub account. :-) Well then. After manually grabbing `trivial-build` and `trivial-exe` into my `local-projects` (aren't they on QL yet?), it seems to work, `(ceramic:setup)` runs through.

(But error #25 is still in place.)

Does that mean I can remove `buildapp` now?

**Comment by eudoxia0** [comment]
Yeah, go ahead and remove buildapp. `trivial-exe` and `trivial-build` will be in the next dist.

**Comment by eudoxia0** [comment]
I think we can close this one. What do you say?
