### ISSUE TITLE
Linux: Can't compile on CCL due to use of Archive

### ISSUE THREAD

**Issue by wnortje** [ceramic/ceramic#22]
To create a CCL image, first replace the buildapp in .ceramic with a custom built CCL version buildapp.

Using this setup fails because Archive isn't implemented for CCL. Archive also does not zip up the tar file.

 I propose that the system installed tar application be used.

**Comment by eudoxia0** [comment]
Right, but this won't work on Windows/CCL because there's no system tar there.
