### ISSUE TITLE
The name "CERAMIC.BUNDLER" does not designate any package

### ISSUE THREAD

**Issue by quicklisp** [ceramic/ceramic#39]
I get this today:

```
The name "CERAMIC.BUNDLER" does not designate any package.
```

Longer log here: http://report.quicklisp.org/2016-04-04/failure-report/ceramic.html#ceramic

**Comment by eudoxia0** [comment]
Ah, yes, the ol' "QL build environment doesn't have QL". Will have a fix ~soon.

**Comment by quicklisp** [comment]
I'm making a Quicklisp dist update tomorrow. Is there any chance this will be fixed by then? Should I keep last month's ceramic instead?

**Comment by eudoxia0** [comment]
Yes, I'm working on this... now

**Comment by eudoxia0** [comment]
I suspect it's working now.
