### ISSUE TITLE
Idle Application Times Out

### ISSUE THREAD

**Issue by jasonmelbye** [ceramic/ceramic#40]
If I let a ceramic application idle for about 5 minutes, it crashes with an I/O timeout error.  5 minutes (300) seconds is the default timeout value for the websocket-timeout slot of the class websocket-acceptor from hunchensocket.  I haven't looked enough to know where/if ceramic could override that, or if it can be set for no timeout.

I'm running with quicklisp 2016-04-21, sbcl 1.2.15, fedora 23

(I mentioned this in #lisp a couple days ago, but had to take off before you responded)

**Comment by eudoxia0** [comment]
Thanks for the heads up, I'll look into changing the timeout.

**Comment by eudoxia0** [comment]
Terribly sorry about the delay, but I believe this fixes it: https://github.com/ceramic/trivial-ws/commit/45b8ae627d9648d5f292f377af67f55e8f2e3aaf

You gotta pull the latest trivial-ws
