### ISSUE TITLE
Can't run basic tutorial - connection refused

### ISSUE THREAD

**Issue by serialhex** [ceramic/ceramic#48]
Hi there.  I'm running ccl 64 on Archlinux and I get the following error:

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: connect ECONNREFUSED 127.0.0.1:40000
    at Object.exports._errnoException (util.js:949:11)
    at exports._exceptionWithHostPort (util.js:972:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
```

in a popup window.  Pressing OK gives me the following:

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: socket hang up
    at createHangUpError (_http_client.js:250:15)
    at Socket.socketCloseListener (_http_client.js:282:23)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:492:12)
```

This is what I ran to get that:

``` lisp
? (ql:quickload :ceramic)
To load "ceramic":
  Load 1 ASDF system:
    ceramic
; Loading "ceramic"
..
(:CERAMIC)
? (ceramic:setup)
Ceramic: Creating Ceramic directories...
Ceramic: Already downloaded. Use :force t to force download.
Ceramic: Preparing the files...
? (ceramic:start)
Ceramic: Starting server...
Ceramic: Starting Electron process...
Ceramic: Waiting for startup...
```

I'm not quite sure what'd going on, it looks like Electron isn't starting up or listening on the port, but right after starting ceramic I get the following:

```
$ ps -Al | grep electron
0 S  1000 24186 24155  9  80   0 - 356435 poll_s pts/6   00:00:00 electron
0 S  1000 24188 24186  0  80   0 - 86432 poll_s pts/6    00:00:00 electron
0 S  1000 24203 24186  1  80   0 - 99227 poll_s pts/6    00:00:00 electron
```

Let me know if there are any other details you would like.  Thanks and have an awesome day!

**Comment by serialhex** [comment]
Also, it doesn't work on Windows Clozure 64-bit (and probably 32-bit), I just tried to run the tests...

```
? (ceramic-test:run-tests)

Running test suite RESOURCE
 Running test RESOURCES ......
 Did 6 checks.
    Pass: 6 (100%)
    Skip: 0 ( 0%)
    Fail: 0 ( 0%)


 Running test SETUP Ceramic: Creating Ceramic directories...
Ceramic: Downloading a copy of Electron...
Downloading "https://github.com/atom/electron/releases/download/v1.2.7/electron-v1.2.7-win32-x64.zip" (Unknown size)
Ceramic: Preparing the files...
.Ceramic: Creating Ceramic directories...
Ceramic: Already downloaded. Use :force t to force download.
Ceramic: Preparing the files...
..
 Did 3 checks.
    Pass: 3 (100%)
    Skip: 0 ( 0%)
    Fail: 0 ( 0%)


Running test suite DRIVER
 Running test LIFECYCLE Ceramic: Starting server...
Ceramic: Starting Electron process...
Ceramic: Waiting for startup...
```

Seems to be the same problem as above...

**Comment by cpc26out** [comment]
FIXED - upgrade electron to current
(snark>This is _ALL_ on the NodeJS/Electron side, imagine that</snark)
Same on OSX 10.11.6 with SBCL
(ceramic:start)
Ceramic: Starting server...
Ceramic: Starting Electron process...
Ceramic: Waiting for startup...

THEN - Electron dumps core

Electron will run stand alone or on restart but not from :start

(these are the steps I took YMMV)
update sbcl and run off master ;; this probably does not matter but funny how SBCL can build from source and not node

update node to 6.6 from pkg <the download> ;; MUST DO node is having build trouble again
update electron to current:  https://github.com/atom/electron/releases/download/ ;; MUST DO
electron-v1.4.1-darwin-x64.zip
in ~/.ceramic/electron rm -r Electron.app
cp Electron.app into ~/.ceramic/electron/

THEN -  (this part adds the default app)

(ceramic:setup)  ; do not :force t
Ceramic: Creating Ceramic directories...
Ceramic: Already downloaded. Use :force t to force download.
Ceramic: Preparing the files...
; No value

;; this is when the magic starts working
CL-USER> (ceramic:start)
Ceramic: Starting server...
Ceramic: Starting Electron process...
Ceramic: Waiting for startup...
127.0.0.1 - [2016-09-24 14:54:35] "GET / HTTP/1.1" 101 0 "-" "-"
Ceramic: Electron started
NIL
CL-USER> (defvar window (ceramic:make-window :url "https://www.google.com/"
                                    :width 800
                                    :height 600))
WINDOW
CL-USER> (ceramic:show window)
NIL
;; "An 800-by-600 pixel browser window pointed at Google should pop up."  <~ As seen on TV

;; MAYBE (defparameter _electron-version_ "1.2.7"
  "The version of Electron to use.")
;;  needs to be updated?
;;  people familiar with code could advise 

;; Thanks!
