### ISSUE TITLE
New Electron does not start on OSX under Ceramic

### ISSUE THREAD

**Issue by svetlyak40wt** [ceramic/ceramic#49]
I've updated Electron with `(ceramic:setup :force t)`, because it just showed gray window in a "bundled" version of the app. And now every time when I do `(ceramic:start)`, I see system window saying "Electron quit unexpectedly".

I started to investigate the reason and come to this minimal example, which just starts electron and produces the same error:

```lisp
(sb-ext:run-program
    "/Users/art/.ceramic/electron/Electron.app/Contents/MacOS/Electron"
    '("https://google.com"))
```

Process exits with code 6 and no output.

I've tried the same in Python, and it starts as expected, without any errors:

```python
import subprocess
subprocess.check_output(
    ('/Users/art/.ceramic/electron/Electron.app/Contents/MacOS/Electron',
     'https://google.com'))
```

**Comment by svetlyak40wt** [comment]
@eudoxia0 Fernando, do you have any thought why this could be?

**Comment by joelreymont** [comment]
This works for me 

```
(sb-ext:run-program
    (truename "~/.ceramic/electron/Electron.app/Contents/MacOS/Electron")
    '("https://google.com"))
```

I do see a bunch of other issues, though 

```
* (ceramic:start)
Ceramic: Starting server...
Ceramic: Starting Electron process...
Ceramic: Waiting for startup...
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
127.0.0.1 - [2017-03-31 13:56:42] "GET / HTTP/1.1" 101 0 "-" "-"
Ceramic: Electron started
```

**Comment by svetlyak40wt** [comment]
Hey guys!

I found that if I start emacs end open an emacs shell. Then command "/Users/art/.ceramic/electron/Electron.app/Contents/MacOS/Electron /Users/art/.ceramic/electron/Electron.app/Contents/Resources/default_app/" fails the same way as when it is started from lisp repl.

But if I start lisp repl without emacs, then `(ceramic:start)` works as expected!

**Comment by svetlyak40wt** [comment]
Solved this by starting a lisp with swank as a separate process and connecting to it from the emacs.

**Comment by jccerrillo** [comment]
Why does Electrum quit when loading Ceramic from emacs?  Would changing emacs or slime/swank configuration fix this?
