### ISSUE TITLE
Tutorial: defvar window fails on Mac

### ISSUE THREAD

**Issue by saanvik** [ceramic/ceramic#5]
I'm running through the tutorial on a Mac with SBCL.

After doing (ceramic:interactive) I tried the window defvar and it fails with a broken pipe:
- (ql:quickload :ceramic)
  To load "ceramic":
  Load 1 ASDF system:
    ceramic
  ; Loading "ceramic"
  ........................
  (:CERAMIC)
- (ceramic:interactive)

T
- (defvar window (ceramic:make-window :url "https://www.google.com/" :width 800 :height 600))

debugger invoked on a SB-INT:SIMPLE-STREAM-ERROR in thread
# <THREAD "main thread" RUNNING {1002D86A13}>:

  Couldn't write to #<SB-SYS:FD-STREAM for "descriptor 7" {1006667253}>:
    Broken pipe

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [ABORT] Exit debugger, returning to top level.

(SB-IMPL::SIMPLE-STREAM-PERROR "Couldn't write to ~s" #<SB-SYS:FD-STREAM for "descriptor 7" {1006667253}> 32)
0] 0

**Comment by eudoxia0** [comment]
Alright, broken pipe. After running `(ceramic:interactive)`, try the following:

First, look at the value of `ceramic::*process*`: it should be something like `#<SB-IMPL::PROCESS [PID] :RUNNING>`.

Then, run this:

``` lisp
(flet ((read-all-from-stream (stream)
         (concatenate 'string
                      (loop for byte = (read-char-no-hang stream nil nil)
                            while byte collecting byte))))
  (loop for stream in (list (external-program:process-output-stream
                             ceramic::*process*)
                            (external-program:process-error-stream
                             ceramic::*process*))
        collecting (read-all-from-stream stream)))
```

**Comment by mikeivanov** [comment]
The process is gone, that's why the pipe is broken.

```
CL-USER> (external-program:process-status ceramic::*process*)
:SIGNALED
5
```

**Comment by mikeivanov** [comment]
I'd suggest setting up a process monitoring thread, so the main program could know when there is no UI and possibly restart it, etc.

**Comment by glider-gun** [comment]
I'm using Mac, and in my environment, it seems Electron itself is corrupted:
`ceramic::*process*` is `#<SB-IMPL::PROCESS [PID] :SIGNALED>` after `(ceramic:interactive)`.
And directly running ~/.ceramic/electron/Electron.app/Contents/MacOS/Electron (from terminal) fails.

It seems get-release is the problematic part (around symbolic link handling?)

I was following sample of http://ceramic.github.io, and after the part of

```
(ql:quickload '(:ceramic :lucerne-utweet))

;; Ensure Ceramic is set up
(ceramic:setup)
```

, I replaced Electron:

First I downloaded electron-v0.28.1-darwin-x64.zip from https://github.com/atom/electron/releases and replaced the Electron with it:

```
$ rm -r ~/.ceramic/electron/
$ rsync -avu ~/Downloads/electron-v0.28.1-darwin-x64/ ~/.ceramic/electron
```

Now `(ceramic:interactive)` opens a Electron default window.
Then I closed the window, and ran (I'm following `(setup)` in driver.lisp)

```
(ceramic.electron.tools:prepare-release (ceramic.electron:release-directory) :operating-system ceramic::*operating-system*)
```

and now the rest of sample code is working in my environment:

```
(ceramic:interactive)

;; Start our app
(lucerne:start utweet.views:app :port 8000)

;; Open a browser window to it
(defvar window (ceramic:make-window :url "http://localhost:8000/"))

(ceramic:show-window window)
```

**Comment by glider-gun** [comment]
for example Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/Current should be symbolic link, but it is not

**Comment by glider-gun** [comment]
It seems `zip:unzip` doesn't handle symbolic links in zip file.

**Comment by mikeivanov** [comment]
On my system (ceramic.electron.tools:binary-pathname ...) returns `/Users/mike/.ceramic/electron/Electron.app/Contents/MacOS/Electron`. Invoking that from the command line yields:

```
$ /Users/mike/.ceramic/electron/Electron.app/Contents/MacOS/Electron
dyld: Library not loaded: @rpath/Electron Framework.framework/Electron Framework
  Referenced from: /Users/mike/.ceramic/electron/Electron.app/Contents/MacOS/Electron
  Reason: no suitable image found.  Did find:
    /Users/mike/.ceramic/electron/Electron.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: file too short
t
Trace/BPT trap: 5
```

**Comment by mikeivanov** [comment]
I think that @glider-gun is correct, it's a `zip:unzip` issue. The simplest solution I could think of would be calling /usr/bin/unzip directly when it's present.

**Comment by glider-gun** [comment]
I've made pull request that uses /usr/bin/unzip if present.

**Comment by eudoxia0** [comment]
Hm. Ideally I'd like to stay within Lisp, since there's no guarantee the user will have such and such tool, but since this PR falls back on `zip:unzip` and OS X ships with `unzip` I'll merge it. Thanks!

**Comment by glider-gun** [comment]
This is maybe not for this page, but `(ceramic.bundler:bundle :markedit)` also fails on OS X and this also seems symlink-related.
`ceramic.util:copy-directory` looks failing in copying "electron" directory, which contains symbolic links for OS X.

stack trace is like:

```
  0: (SB-IMPL::SIMPLE-FILE-PERROR "error opening ~S" #P"/Users/user/.ceramic/electron/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/Libraries" 2)
  1: ((FLET SB-IMPL::VANILLA-OPEN-ERROR :IN OPEN))
  2: (OPEN #P"/Users/user/.ceramic/electron/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/Libraries" :DIRECTION :INPUT :ELEMENT-TYPE (UNSIGNED-BYTE 8) :IF-EXISTS NIL ..
  3: (UIOP/STREAM:CONCATENATE-FILES (#P"/Users/user/.ceramic/electron/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/Libraries") #P"/Users/user/.ceramic/working/elec..
  4: ((LABELS CL-FAD::WALK :IN CL-FAD:WALK-DIRECTORY) #P"/Users/user/.ceramic/electron/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/")
  5: ((LABELS CL-FAD::WALK :IN CL-FAD:WALK-DIRECTORY) #P"/Users/user/.ceramic/electron/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/")
  6: ((LABELS CL-FAD::WALK :IN CL-FAD:WALK-DIRECTORY) #P"/Users/user/.ceramic/electron/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/")
  7: ((LABELS CL-FAD::WALK :IN CL-FAD:WALK-DIRECTORY) #P"/Users/user/.ceramic/electron/Electron.app/Contents/Frameworks/Electron Framework.framework/")
  8: ((LABELS CL-FAD::WALK :IN CL-FAD:WALK-DIRECTORY) #P"/Users/user/.ceramic/electron/Electron.app/Contents/Frameworks/")
  9: ((LABELS CL-FAD::WALK :IN CL-FAD:WALK-DIRECTORY) #P"/Users/user/.ceramic/electron/Electron.app/Contents/")
 10: ((LABELS CL-FAD::WALK :IN CL-FAD:WALK-DIRECTORY) #P"/Users/user/.ceramic/electron/Electron.app/")
 11: ((LABELS CL-FAD::WALK :IN CL-FAD:WALK-DIRECTORY) #P"/Users/user/.ceramic/electron/")
 12: (CL-FAD:WALK-DIRECTORY #P"/Users/user/.ceramic/electron/" #<CLOSURE (LAMBDA (PATHNAME) :IN CERAMIC.UTIL:COPY-DIRECTORY) {100B89DBBB}> :DIRECTORIES :BREADTH-FIRST :IF-DOES-NOT-EXIST :ERROR :TEST NIL ..
 13: (CERAMIC.UTIL:COPY-DIRECTORY #P"/Users/user/.ceramic/electron/" #P"/Users/user/.ceramic/working/electron/")
 14: (CERAMIC.BUNDLER:BUNDLE :MARKEDIT :BUNDLE-PATHNAME NIL)
 15: (SB-INT:SIMPLE-EVAL-IN-LEXENV (CERAMIC.BUNDLER:BUNDLE :MARKEDIT) #<NULL-LEXENV>)
 16: (EVAL (CERAMIC.BUNDLER:BUNDLE :MARKEDIT))
 --more--
```

**Comment by eudoxia0** [comment]
hm, I'll have to look into the implementation of copy-directory. I think this will probably be a simple fix.

**Comment by hoytech** [comment]
FWIW I ran into the same problem with my perl bindings for valence (https://github.com/hoytech/valence).

I didn't really look too deeply into why it failed (I don't even own a mac) I just ended up calling "unzip -oqq" to unzip it directly into the install path:

https://github.com/hoytech/Alien-Electron/blob/master/ElectronModuleBuild.pm#L32

I do agree it would be preferable to not rely on the unzip binary.

Ceramic is a really neat project by the way!

Cheers,

Doug

**Comment by eudoxia0** [comment]
@hoytech huh, what a coincidence, another lisper working on this!

Ok, I think d7876cf fixes the symlinks issue.

**Comment by eudoxia0** [comment]
Has anyone had a chance to try this and see how far they get?

**Comment by glider-gun** [comment]
Currently I can't touch my macbook and have little internet connection until Saturday, but I'll try after that.
I'm sorry for late reply.

**Comment by saanvik** [comment]
Just saw this today.

I did

git pull origin master
sbcl
- (ql:quickload :ceramic)
- (ceramic.file:wipe-data)

then continued with the tutorial and saw a window with the Google landing
page.  Looks like it's all fixed.

**Comment by eudoxia0** [comment]
Awesome! I'm gonna close this now, and if run into other problems, let's discuss those in a more specific issue.
