### ISSUE TITLE
Ceramic:bundle (or trivial-build) does not find my component

### ISSUE THREAD

**Issue by vindarel** [ceramic/ceramic#51]
Hi all,
I've successfully launched an Electron window with `ceramic:show` but I am unable to `build` a bundle. It looks like `trivial-build` can not find my component, even though I can quickload my project or `asdf:load-system` it on the REPL without errors.

Now if you excuse me, I gave my process and the stacktraces on SO: https://stackoverflow.com/questions/46199020/uiop-run-programsubprocess-error-and-not-showing-much

I'd love to hear your tips to debug this. Also let me know if I'd better reach trivial-build or uiop.

Regards

**Comment by eudoxia0** [comment]
Just a brief observation, the command on SO: `(format nil "(load #p\"/home/vince/projets/weblocks-todomvc/weblocks-todomvc.asd/\"")` is invalid: the format control string opens with `(load` but doesn't have a matching closing parenthesis.
