### ISSUE TITLE
ceramic-test fails with ASDF 3.3.1 - threat to remove from QL january update

### ISSUE THREAD

**Issue by vindarel** [ceramic/ceramic#55]
Seen on http://blog.quicklisp.org/2018/01/build-failures-with-asdf-331.html Threatens to remove the project from QL's january dist update.

bug report: http://report.quicklisp.org/2018-01-16/failure-report/ceramic.html#ceramic-test

`; caught ERROR: ;   READ error during COMPILE-FILE: Package CERAMIC.BUNDLER does not exist. Line: 30, Column: 29, File-Position: 855 Stream: #<SB-INT:FORM-TRACKING-STREAM for "file /home/quicklisp/quicklisp-controller/dist/build-cache/ceramic/3a103acdb6b4ca4a2ea83d63f82192dfe719c7e4/ceramic-20180116-git/t/integration.lisp" {100E1A6B13}> Unhandled UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING {1001DB0083}>: COMPILE-FILE-ERROR while compiling #<CL-SOURCE-FILE "ceramic-test" "t" "integration">`

(edit) maybe is it a gentle failure, not threatening.

**Comment by eudoxia0** [comment]
Fixed by https://github.com/CommonDoc/codex/pull/19 - thanks for reporting!
