### ISSUE TITLE
Ceramic not quickloading on Windows SBCL.

### ISSUE THREAD

**Issue by BanishedBliss** [ceramic/ceramic#66]
I load ceramic via
```lisp
(ql:quickload '(:ceramic :lucerne-utweet))
```
and I get the following error:
```
COMPILE-FILE-ERROR while
compiling #<CL-SOURCE-FILE "ceramic" "src" "os">
   [Condition of type UIOP/LISP-BUILD:COMPILE-FILE-ERROR]
```
```
<previous steps>
[package trivial-ws]..............................
[package remote-js]...............................
[package ceramic.error]...........................
[package ceramic.os]
; 
; caught ERROR:
;   READ error during COMPILE-FILE:
;   
;     Package LOG does not exist.
;   
;       Line: 35, Column: 11, File-Position: 881
;   
;       Stream: #<SB-INT:FORM-TRACKING-STREAM for "file C:\\Users\\PepperMint\\quicklisp\\dists\\ultralisp\\software\\40ants-ceramic-20190317212613\\src\\os.lisp" {1001C01CB3}>
; Debugger entered on #<UIOP/LISP-BUILD:COMPILE-FILE-ERROR {1001C78FF3}>
```

**Comment by noncom** [comment]
Same error here, just came to report too.

**Comment by mmontone** [comment]
This is error not from this repository, but from a fork: https://github.com/40ants/ceramic

I think if you use Ultralisp you don't have control over which fork of Ceramic is loaded ...

**Comment by noncom** [comment]
Oh indeed. Both in the OPs and my case the path actually says that it's the fork by 40ants.
And welp, that fork doesn't even have the issues section, and it's just as ancient :/

Likely, the solution is once again a custom clone of the ceramic repo.
I'll try that a bit later and see if it works.

**Comment by eudoxia0** [comment]
I thank you all for your interest. But I have not actively written code for this project since 2016. I have limited interest in maintaining it. I might accept a PR, but I don't have the time or desire to triage issues and fix them.

**Comment by noncom** [comment]
> Likely, the solution is once again a custom clone of the ceramic repo. I'll try that a bit later and see if it works.

It worked. So if you have this problem, just clone this repo manually, and don't rely on Ultralisp for that.
